In [2]:
#1. What is a Python library? Why ^o we use Python libraries?
'''A Python library is a collection of pre-written code, functions, and modules that extend the capabilities of the Python programming language. 
These libraries provide reusable and well-tested code, allowing developers to perform various tasks without having to implement everything from scratch. 
Python libraries cover a wide range of functionalities, such as data manipulation, scientific computing, web development, machine learning, artificial intelligence, and more.

**********Here are some key reasons why Python libraries are widely used:*************

1.)Efficiency: Libraries save time and effort by providing pre-built solutions for common tasks. Developers can leverage these libraries to avoid reinventing the wheel and 
focus on solving specific problems.

2.)Code Reusability: Python libraries encapsulate functionality into modules and functions that can be easily reused across different projects. 
This promotes a modular and efficient coding style, making it easier to maintain and update code.

3.)Community Support: Many Python libraries are open-source and have large, active communities. 
This means that developers can benefit from community-contributed improvements, bug fixes, and documentation, making it easier to find solutions and support.

4.)Standardization: Python libraries often establish standard practices and conventions, contributing to a consistent coding style. 
This helps developers maintain clean and readable code that follows industry best practices.

5.)Extensibility: Python libraries can be easily extended to accommodate specific needs. 
If a library lacks a particular feature, developers can contribute to the library or build their own extensions, fostering a collaborative and adaptable ecosystem.

6.)Versatility: Python has a rich ecosystem of libraries catering to various domains, making it a versatile language. 
Whether you're working on web development, data analysis, machine learning, or other fields, chances are there's a library that can simplify your tasks.

7.)Performance: Many Python libraries are implemented in languages like C or C++, providing efficient performance for computationally intensive tasks.
Developers can enjoy the ease of Python coding without sacrificing performance when using such libraries.

In summary, Python libraries enhance the capabilities of the language by providing pre-built solutions for common tasks, promoting code reusability, and 
fostering a collaborative and efficient development environment.
'''


In [ ]:
#2. What is the ^ifference between Numpy array an^ List?
'''
NumPy arrays and Python lists are both used to store collections of data, but there are significant differences between them in terms of functionality, performance, 
and usage. Here are some key distinctions:

1. 1.Data Type and Homogeneity:**
   - **NumPy Array:** NumPy arrays are homogeneous, meaning all elements must be of the same data type. This allows for more efficient storage and operations on the data.
   - **List:** Python lists are heterogeneous, allowing elements of different data types to coexist in the same list.

2. 2.)erformance:**
   **NumPy Array:** NumPy is optimized for numerical operations. Its array operations are implemented in C and Fortran, providing better performance compared to Python lists
   for mathematical computations.
   
   **List:** Lists are more general-purpose and not optimized for numerical operations. Performing mathematical operations on large lists can be slower compared to NumPy arrays.

3. 3.)emory Efficiency:**
   **NumPy Array:** NumPy arrays are more memory-efficient than lists, especially for large datasets. This is partly due to the homogeneous data type, which allows for a 
   more compact representation in memory.
   **List:** Lists have more overhead in terms of memory because they store additional information for each element, such as the type and reference.

4. 4.)ase of Use:**
   **NumPy Array:** NumPy provides a wide range of mathematical functions and operations on arrays, making it convenient for numerical computing. It supports vectorized 
       operations, which can be more concise and readable.
   **List:** Lists are more general-purpose and versatile. They are easier to work with for tasks that don't involve extensive numerical computations.

5. 5.)yntax and Operations:**
   **NumPy Array:** NumPy supports element-wise operations, broadcasting, and other advanced array manipulation techniques. It provides a more concise and expressive syntax 
           or numerical operations.
   **List:** Lists are more basic in terms of operations. To perform mathematical operations on all elements of a list, you would typically use loops or list comprehensions.
   

6. 6.)ize and Extensibility:**
   **NumPy Array:** The size of a NumPy array is fixed upon creation. If you need to add or remove elements, you'll create a new array. 
   NumPy arrays are more suitable for fixed-size, numerical datasets.
   **List:** Lists can dynamically grow or shrink in size, making them more flexible for dynamic data structures.

In summary, while both NumPy arrays and Python lists serve the purpose of storing collections of data, NumPy arrays are specifically designed for numerical computing, 
offering better performance and memory efficiency. Lists, on the other hand, are more general-purpose and flexible for a wide range of applications. 
The choice between them depends on the nature of the data and the operations you need to perform.


In [7]:
#3. Fin^ the shape, size an^ ^imension of the following array?
import numpy as np
l = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
np.shape(l)

(3, 4)

In [12]:
#4. Write python code to access the first row of the following array?
kl = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"First row = {kl[0]}")

First row = [1 2 3 4]


In [13]:
#5. How to you access the element at the third row and fourth column from the given numpy array?
lk = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"Access element in 3rd row and 4th column = {kl[2,3]}")

Access element in 3rd row and 4th column = 12


In [15]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
po = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"Extract all odd-indexed element from given array = {po[:, 1::2]}")

Extract all odd-indexed element from given array = [[ 2  4]
 [ 6  8]
 [10 12]]


In [21]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
'''np.random.rand(3, 3) creates a 3x3 matrix with random values sampled from a uniform distribution over the interval [0, 1). 
Each element of the matrix will be a float between 0 (inclusive) and 1 (exclusive).
'''
h = np.random.rand(3,3)
print(f"generating a random 3x3 matrix with values between 0 and 1 = {h}")

generating a random 3x3 matrix with values between 0 and 1 = [[0.27201912 0.61060945 0.73682847]
 [0.72400361 0.64735261 0.12835794]
 [0.19579672 0.23106224 0.35967672]]


In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn?
'''
The main difference between `np.random.rand` and `np.random.randn` lies in the type of distribution used to generate random numbers:

1. **`np.random.rand`:**
   - This function generates random numbers from a uniform distribution over the interval `[0, 1)`.
   - All values in the resulting array are equally likely to occur.
   - The function takes the shape of the output array as separate arguments. For example, `np.random.rand(3, 3)` generates a 3x3 array of random numbers between 0 and 1.

   Example:
   ```python
   import numpy as np

   random_uniform = np.random.rand(3, 3)
   ```

2. **`np.random.randn`:**
   - This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1), which is also known as a Gaussian or normal distribution.
   - Values closer to 0 are more likely to occur, and the distribution follows a bell-shaped curve.
   - Like `np.random.rand`, the function takes the shape of the output array as separate arguments. 
       For example, `np.random.randn(3, 3)` generates a 3x3 array of random numbers from a standard normal distribution.

   Example:
   ```python
   import numpy as np

   random_normal = np.random.randn(3, 3)
   ```

In summary:

- Use `np.random.rand` for generating random numbers from a uniform distribution over the interval `[0, 1)`.
- Use `np.random.randn` for generating random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

Both functions are part of NumPy's `random` module and are useful in different scenarios depending on the desired distribution of the generated random numbers.
'''

In [34]:
#9. Write code to increase the dimension of the following array?
f = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
#This will reshape but not modify thre original array --->f.reshape(2,2,3)
f.resize(2, 2, 3)
#"This will modify thre original array ---> f.resize(2, 2, 3)
print(f)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
#10. How to transpose the following array in NumPy?
f = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
po = f.transpose()
po

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [37]:
f.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [44]:
#11. Consi^er the following matrix:
import numpy as np

# Matrix A2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Matrix B2
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

#Perform the following operation using Python1
#a) Index wiLe multiplication
result_matrix = A2 * B2

print(f"Index wise multiplication = {result_matrix}")


#b) Matix multiplication
result_matrix1 = np.dot(A2, B2.T)  # Using the transpose (.T) of B2 to ensure valid dimensions
print(f"Matrix multiplication = {result_matrix1}")

# Alternatively, you can use the @ operator for matrix multiplication
# result_matrix = A2 @ B2.T

#c)Add both the matrics
print(f"Add both the matrics = {A2 + B2}")

#d) Subtact matix B from A
print(f"Subtract both the matrics = {A2 - B2}")

#e)Diide Matix B by A
print(f"Diide Matix B by A = {B2/A2}")


Index wise multiplication = [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication = [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Add both the matrics = [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtract both the matrics = [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Diide Matix B by A = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12. Which function in Numpy can be used to swap the byte order of an array?
'''
The `byteswap` function in NumPy can be used to swap the byte order of an array. 
This function is available for ndarray objects and allows you to change the byte order of the elements in the array. 
It is particularly useful when dealing with data stored in a different byte order, such as when reading binary data from files or network communication.

Here's an example of how to use `byteswap`:

```python
import numpy as np

# Create a NumPy array with a specified byte order
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order using byteswap
swapped_array = original_array.byteswap()

print("Original Array:", original_array)
print("Swapped Array:", swapped_array)
```

This will output something like:

```
Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]
```

Keep in mind that the byte order swap may not result in a meaningful output for integer values unless the byte order is different from the system's native byte order. 
For floating-point numbers or data read from external sources, byte order swapping is more relevant.
'''

In [46]:
#13. What is the significance of the np.linalg.inv function?
'''
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. 
The significance of the inv function lies in its application to linear algebra and solving systems of linear equations.

Given a square matrix A,if its inverse exists (i.e.,A^(-1) exists),then the product of A and A^(-1) is the identity matrix I.
A. A^(-1)  =  A^(-1) .A = I

Here are some key points regarding the significance of np.linalg.inv:

1.)Solving Linear Systems:
One of the primary applications of matrix inversion is in solving systems of linear equations. If Ax = B,where A is a square matrix, x is the column vector of variables, 
and B is another vector, then x = A^(-1).B.This is particularly useful in various fields, including physics, engineering, and data analysis.

2.)Eigenvalue Problems:
Matrix inversion is often used in eigenvalue problems. For a square matrix A,if Av = λv,where v is a non-zero vector and λ is an eigenvalue,then A^(-1)v = 1/λ *v.
This relationship is useful in understanding the properties of eigenvalues and eigenvectors.

3.)Numerical Stability:
The np.linalg.inv function uses numerical algorithms to compute the matrix inverse. It's important to note that not all matrices have inverses, and in some cases, 
the numerical precision of floating-point calculations may affect the accuracy of the computed inverse. Checking the condition number of a matrix (using np.linalg.cond) 
can provide insights into the numerical stability.
Here's a simple example of using np.linalg.inv to solve a linear system:
'''
import numpy as np

# Define a coefficient matrix A and a column vector B
A = np.array([[2, 1], [3, 4]])
B = np.array([4, 7])

# Solve for x in Ax = B using np.linalg.inv
x = np.linalg.inv(A).dot(B)

print("Solution x:", x)



Solution x: [1.8 0.4]


In [ ]:
#14. What does the np.reshape function do, and how is it used?
'''
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape, and 
the original array remains unchanged. The reshaped array has the same data as the original array but organized in a different way.
'''
f = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
#This will reshape but not modify thre original array --->f.reshape(2,2,3)
